import plotly.graph_objects as go
from functools import reduce 
import pandas as pd
from math import log
import dash
import dash_core_components as dcc
import dash_html_components as html
import dataframes

def setup():
    app = dash.Dash()
    app.layout = html.Div([
        dcc.Dropdown(
            id='xvar_dropdown',
            options=[
                {'label': 'Broadband Subscriptions', 'value': 'broadband-subscriptions'},
                {'label': 'Child Mortality', 'value': 'child-mortality'},
                {'label': 'CO2 Emissions', 'value': 'co2'},
                {'label': 'Disability Adjusted Life Years', 'value': 'dalys'},
                {'label': 'Age Dependency Ratio', 'value': 'dependency'},
                {'label': 'Deaths from Drugs and Alcohol', 'value': 'drug-deaths'},
                {'label': 'Years of Expected Schooling', 'value': 'expected-schooling'},
                {'label': 'Female Labor Force Participation Rate', 'value': 'female-labor'},
                {'label': 'Government Expenditure per Capita', 'value': 'gov-expenditure'},
                {'label': 'Happiness', 'value': 'happiness'},
                {'label': 'Homicides', 'value': 'homicides'},
                {'label': 'Life Expectancy', 'value': 'life-expectancy'},
                {'label': 'Deaths from Pollution', 'value': 'pollution-deaths'},
                {'label': 'Savings', 'value': 'savings'}
            ],
            value="broadband-subscriptions"
        ),
        html.Div(id='xvar-output-container'),
        dcc.Dropdown(
            id='yvar_dropdown',
            options=[
                {'label': 'Broadband Subscriptions', 'value': 'broadband-subscriptions'},
                {'label': 'Child Mortality', 'value': 'child-mortality'},
                {'label': 'CO2 Emissions', 'value': 'co2'},
                {'label': 'Disability Adjusted Life Years', 'value': 'dalys'},
                {'label': 'Age Dependency Ratio', 'value': 'dependency'},
                {'label': 'Deaths from Drugs and Alcohol', 'value': 'drug-deaths'},
                {'label': 'Years of Expected Schooling', 'value': 'expected-schooling'},
                {'label': 'Female Labor Force Participation Rate', 'value': 'female-labor'},
                {'label': 'Government Expenditure per Capita', 'value': 'gov-expenditure'},
                {'label': 'Happiness', 'value': 'happiness'},
                {'label': 'Homicides', 'value': 'homicides'},
                {'label': 'Life Expectancy', 'value': 'life-expectancy'},
                {'label': 'Deaths from Pollution', 'value': 'pollution-deaths'},
                {'label': 'Savings', 'value': 'savings'}
            ],
            value="child-mortality"
        ),
        html.Div(id='yvar-output-container'),
        dcc.Dropdown(
            id='bubblevar_dropdown',
            options=[
                {'label': 'Broadband Subscriptions', 'value': 'broadband-subscriptions'},
                {'label': 'Child Mortality', 'value': 'child-mortality'},
                {'label': 'CO2 Emissions', 'value': 'co2'},
                {'label': 'Disability Adjusted Life Years', 'value': 'dalys'},
                {'label': 'Age Dependency Ratio', 'value': 'dependency'},
                {'label': 'Deaths from Drugs and Alcohol', 'value': 'drug-deaths'},
                {'label': 'Years of Expected Schooling', 'value': 'expected-schooling'},
                {'label': 'Female Labor Force Participation Rate', 'value': 'female-labor'},
                {'label': 'Government Expenditure per Capita', 'value': 'gov-expenditure'},
                {'label': 'Happiness', 'value': 'happiness'},
                {'label': 'Homicides', 'value': 'homicides'},
                {'label': 'Life Expectancy', 'value': 'life-expectancy'},
                {'label': 'Deaths from Pollution', 'value': 'pollution-deaths'},
                {'label': 'Savings', 'value': 'savings'}
            ],
            value='co2'
        ),
        html.Div(id='bubblevar-output-container'),
        dcc.Dropdown(
            id = 'country-dropdown',
            options=[
                {'label': 'Afghanistan', 'value': 'AFG'},
                {'label': 'Albania', 'value': 'ALB'},
                {'label': 'Algeria', 'value': 'DZA'},
                {'label': 'Andorra', 'value': 'AND'},
                {'label': 'Angola', 'value': 'AGO'},
                {'label': 'Anguilla', 'value': 'AIA'},
                {'label': 'Antigua and Barbuda', 'value': 'ATG'},
                {'label': 'Argentina', 'value': 'ARG'},
                {'label': 'Armenia', 'value': 'ARM'},
                {'label': 'Aruba', 'value': 'ABW'},
                {'label': 'Australia', 'value': 'AUS'},
                {'label': 'Austria', 'value': 'AUT'},
                {'label': 'Azerbaijan', 'value': 'AZE'},
                {'label': 'Bahamas', 'value': 'BHS'},
                {'label': 'Bahrain', 'value': 'BHR'},
                {'label': 'Bangladesh', 'value': 'BGD'},
                {'label': 'Barbados', 'value': 'BRB'},
                {'label': 'Belarus', 'value': 'BLR'},
                {'label': 'Belgium', 'value': 'BEL'},
                {'label': 'Belize', 'value': 'BLZ'},
                {'label': 'Benin', 'value': 'BEN'},
                {'label': 'Bhutan', 'value': 'BTN'},
                {'label': 'Bolivia', 'value': 'BOL'},
                {'label': 'Bosnia and Herzegovina', 'value': 'BIH'},
                {'label': 'Botswana', 'value': 'BWA'},
                {'label': 'Brazil', 'value': 'BRA'},
                {'label': 'Brunei', 'value': 'BRN'},
                {'label': 'Bulgaria', 'value': 'BGR'},
                {'label': 'Burkina Faso', 'value': 'BFA'},
                {'label': 'Burundi', 'value': 'BDI'},
                {'label': 'Cambodia', 'value': 'KHM'},
                {'label': 'Cameroon', 'value': 'CMR'},
                {'label': 'Canada', 'value': 'CAN'},
                {'label': 'Cape Verde', 'value': 'CPV'},
                {'label': 'Central African Republic', 'value': 'CAF'},
                {'label': 'Chad', 'value': 'TCD'},
                {'label': 'Chile', 'value': 'CHL'},
                {'label': 'China', 'value': 'CHM'},
                {'label': 'Colombia', 'value': 'COL'},
                {'label': 'Comoros', 'value': 'COM'},
                {'label': 'Congo', 'value': 'COG'},
                {'label': 'Cook Islands', 'value': 'COK'},
                {'label': 'Costa Rica', 'value': 'CRI'},
                {'label': "Cote d'Ivoire", 'value': 'CIV'},
                {'label': 'Croatia', 'value': 'HRV'},
                {'label': 'Cuba', 'value': 'CUB'},
                {'label': 'Curacao', 'value': 'CUW'},
                {'label': 'Cyprus', 'value': 'CYP'},
                {'label': 'Czechia', 'value': 'CZE'},
                {'label': 'Democratic Republic of Congo', 'value': 'COD'},
                {'label': 'Denmark', 'value': 'DNK'},
                {'label': 'Djibouti', 'value': 'DJI'},
                {'label': 'Dominica', 'value': 'DMA'},
                {'label': 'Dominican Republic', 'value': 'DOM'},
                {'label': 'Ecuador', 'value': 'ECU'},
                {'label': 'Egypt', 'value': 'EGY'},
                {'label': 'El Salvador', 'value': 'SLV'},
                {'label': 'Equatorial Guinea', 'value': 'GNQ'},
                {'label': 'Eritrea', 'value': 'ERI'},
                {'label': 'Estonia', 'value': 'EST'},
                {'label': 'Eswatini', 'value': 'SWZ'},
                {'label': 'Ethiopia', 'value': 'ETH'},
                {'label': 'Fiji', 'value': 'FJI'},
                {'label': 'Finland', 'value': 'FIN'},
                {'label': 'France', 'value': 'FRA'},
                {'label': 'French Guiana', 'value': 'GUF'},
                {'label': 'Gabon', 'value': 'GAB'},
                {'label': 'Gambia', 'value': 'GMB'},
                {'label': 'Georgia', 'value': 'GEO'},
                {'label': 'Germany', 'value': 'DEU'},
                {'label': 'Ghana', 'value': 'GHA'},
                {'label': 'Greece', 'value': 'GRC'},
                {'label': 'Grenada', 'value': 'GRD'},
                {'label': 'Guam', 'value': 'GUM'},
                {'label': 'Guatemala', 'value': 'GTM'},
                {'label': 'Guinea', 'value': 'GIN'},
                {'label': 'Guinea-Bissau', 'value': 'GNM'},
                {'label': 'Guyana', 'value': 'GUY'},
                {'label': 'Haiti', 'value': 'HTI'},
                {'label': 'Honduras', 'value': 'HND'},
                {'label': 'Hong Kong', 'value': 'HKG'},
                {'label': 'Hungary', 'value': 'HUN'},
                {'label': 'Iceland', 'value': 'ISL'},
                {'label': 'India', 'value': 'IND'},
                {'label': 'Indonesia', 'value': 'IDN'},
                {'label': 'Iran', 'value': 'IRN'},
                {'label': 'Iraq', 'value': 'IRQ'},
                {'label': 'Ireland', 'value': 'IRL'},
                {'label': 'Israel', 'value': 'ISR'},
                {'label': 'Italy', 'value': 'ITA'},
                {'label': 'Jamaica', 'value': 'JAM'},
                {'label': 'Japan', 'value': 'JPN'},
                {'label': 'Jordan', 'value': 'JOR'},
                {'label': 'Kazakhstan', 'value': 'KAZ'},
                {'label': 'Kenya', 'value': 'KEN'},
                {'label': 'Kiribati', 'value': 'KIR'},
                {'label': 'Kuwait', 'value': 'KWT'},
                {'label': 'Kyrgyzstan', 'value': 'KGZ'},
                {'label': 'Laos', 'value': 'LAO'},
                {'label': 'Latvia', 'value': 'LVA'},
                {'label': 'Lebanon', 'value': 'LBN'},
                {'label': 'Lesotho', 'value': 'LSO'},
                {'label': 'Liberia', 'value': 'LBR'},
                {'label': 'Libya', 'value': 'LBY'},
                {'label': 'Lithuania', 'value': 'LTU'},
                {'label': 'Luxembourg', 'value': 'LUX'},
                {'label': 'Macao', 'value': 'MAC'},
                {'label': 'Madagascar', 'value': 'MDG'},
                {'label': 'Malawi', 'value': 'MWI'},
                {'label': 'Malaysia', 'value': 'MYS'},
                {'label': 'Maldives', 'value': 'MDV'},
                {'label': 'Mali', 'value': 'MLI'},
                {'label': 'Malta', 'value': 'MLT'},
                {'label': 'Marshall Islands', 'value': 'MHL'},
                {'label': 'Martinique', 'value': 'MTQ'},
                {'label': 'Mauritania', 'value': 'MRT'},
                {'label': 'Mauritius', 'value': 'MUS'},
                {'label': 'Mayotte', 'value': 'MYT'},
                {'label': 'Mexico', 'value': 'MEX'},
                {'label': 'Micronesia', 'value': 'FSM'},
                {'label': 'Moldova', 'value': 'MDA'},
                {'label': 'Monaco', 'value': 'MCO'},
                {'label': 'Mongolia', 'value': 'MNG'},
                {'label': 'Montenegro', 'value': 'MNE'},
                {'label': 'Morocco', 'value': 'MAR'},
                {'label': 'Mozambique', 'value': 'MOZ'},
                {'label': 'Myanmar', 'value': 'MMR'},
                {'label': 'Namibia', 'value': 'NAM'},
                {'label': 'Nauru', 'value': 'NRU'},
                {'label': 'Nepal', 'value': 'NPL'},
                {'label': 'Netherlands', 'value': 'NLD'},
                {'label': 'New Caledonia', 'value': 'NCL'},
                {'label': 'New Zealand', 'value': 'NZL'},
                {'label': 'Nicaragua', 'value': 'NIC'},
                {'label': 'Niger', 'value': 'NER'},
                {'label': 'Nigeria', 'value': 'NGA'},
                {'label': 'Niue', 'value': 'NIU'},
                {'label': 'North Korea', 'value': 'PRK'},
                {'label': 'North Macedonia', 'value': 'MKD'},
                {'label': 'Oman', 'value': 'OMN'},
                {'label': 'Pakistan', 'value': 'PAK'},
                {'label': 'Palau', 'value': 'PLW'},
                {'label': 'Palestine', 'value': 'PSE'},
                {'label': 'Panama', 'value': 'PAN'},
                {'label': 'Papua New Guinea', 'value': 'PNG'},
                {'label': 'Paraguay', 'value': 'PRY'},
                {'label': 'Peru', 'value': 'PER'},
                {'label': 'Philippines', 'value': 'PHL'},
                {'label': 'Poland', 'value': 'POL'},
                {'label': 'Portugal', 'value': 'PRT'},
                {'label': 'Puerto Rico', 'value': 'PRI'},
                {'label': 'Qatar', 'value': 'QAT'},
                {'label': 'Romania', 'value': 'ROU'},
                {'label': 'Russia', 'value': 'RUS'},
                {'label': 'Rwanda', 'value': 'RWA'},
                {'label': 'Saint Kitts and Nevis', 'value': 'KNA'},
                {'label': 'Saint Lucia', 'value': 'LCA'},
                {'label': 'Saint Vincent and the Grenadines', 'value': 'VCT'},
                {'label': 'Samoa', 'value': 'WSM'},
                {'label': 'San Marino', 'value': 'SMR'},
                {'label': 'Sao Tome and Principe', 'value': 'STP'},
                {'label': 'Saudi Arabia', 'value': 'SAU'},
                {'label': 'Senegal', 'value': 'SEN'},
                {'label': 'Serbia', 'value': 'SRB'},
                {'label': 'Seychelles', 'value': 'SYC'},
                {'label': 'Sierra Leone', 'value': 'SLE'},
                {'label': 'Singapore', 'value': 'SGP'},
                {'label': 'Slovakia', 'value': 'SVK'},
                {'label': 'Slovenia', 'value': 'SVN'},
                {'label': 'Solomon Islands', 'value': 'SLB'},
                {'label': 'Somalia', 'value': 'SOM'},
                {'label': 'South Africa', 'value': 'ZAF'},
                {'label': 'South Korea', 'value': 'KOR'},
                {'label': 'South Sudan', 'value': 'SSD'},
                {'label': 'Spain', 'value': 'ESP'},
                {'label': 'Sri Lanka', 'value': 'LKA'},
                {'label': 'Sudan', 'value': 'SDN'},
                {'label': 'Suriname', 'value': 'SUR'},
                {'label': 'Switzerland', 'value': 'CHE'},
                {'label': 'Syria', 'value': 'SYR'},
                {'label': 'Tajikistan', 'value': 'TJK'},
                {'label': 'Tanzania', 'value': 'TZA'},
                {'label': 'Tajikistan', 'value': 'TJK'},
                {'label': 'Thailand', 'value': 'THA'},
                {'label': 'Timor', 'value': 'TLS'},
                {'label': 'Togo', 'value': 'TGO'},
                {'label': 'Tonga', 'value': 'TON'},
                {'label': 'Trinidad and Tobago', 'value': 'TTO'},
                {'label': 'Tunisia', 'value': 'TUN'},
                {'label': 'Turkey', 'value': 'TUR'},
                {'label': 'Turkmenistan', 'value': 'TKM'},
                {'label': 'Tuvalu', 'value': 'TUV'},
                {'label': 'Uganda', 'value': 'UGA'},
                {'label': 'Ukraine', 'value': 'UKR'},
                {'label': 'United Arab Emirates', 'value': 'ARE'},
                {'label': 'United Kingdom', 'value': 'GBR'},
                {'label': 'United States', 'value': 'USA'},
                {'label': 'Uzbekistan', 'value': 'UZB'},
                {'label': 'Vanuatu', 'value': 'VUT'},
                {'label': 'Venezuela', 'value': 'VEN'},
                {'label': 'Vietnam', 'value': 'VNM'},
                {'label': 'Yemen', 'value': 'YEM'},
                {'label': 'Zambia', 'value': 'ZMB'},
                {'label': 'Zimbabwe', 'value': 'ZWE'}
            ],
            value=top_twenty,
            multi=True
        ),
        html.Div(id='dd-output-container'),  
        dcc.Graph(figure=fig)
    ])
    @app.callback(
        dash.dependencies.Output('dd-output-container', 'children'),
        [dash.dependencies.Input('country-dropdown', 'value')])
    def update_output(value):
        return 'You have selected "{}"'.format(value)


    if __name__ == '__main__':
        app.run_server(debug=True)
    app.run_server(debug=True, use_reloader=False)